Error Flow

diff --git a/.github/workflows/integrity-check.yml b/.github/workflows/integrity-check.yml
--- a/.github/workflows/integrity-check.yml
+++ b/.github/workflows/integrity-check.yml
@@ -25,4 +25,4 @@ jobs:
     - name: Build Yamale Recipe
       run: python scripts/yamale_build.py
     - name: Check diff
-      run: git diff --quiet -- || echo "You need to run \`python scripts/yamale_build.py\`"
+      run: git diff --quiet -- || echo "::error You need to run \`python scripts/yamale_build.py\`"
