Workflow no error

diff --git a/.github/workflows/integrity-check.yml b/.github/workflows/integrity-check.yml
--- a/.github/workflows/integrity-check.yml
+++ b/.github/workflows/integrity-check.yml
@@ -24,6 +24,6 @@ jobs:
       with:
         command: run build_yamale
 
-    - name: Build Yamale Recipe
-      run: git diff --quiet -- || (echo "::error file=yamale,line=0,col=0::You need to run `python scripts/yamale_build.py`" && exit 1)
+    - name: Check Yamale Recipe for changes
+      run: git diff --quiet -- || (echo "::error file=yamale,line=0,col=0::You need to run 'python scripts/yamale_build.py'" && exit 1)
 
