Atomise build tasks (#14)
Changes include:

    Build parts are now much more atomic
    Media files are read in groups, and can change for each export.
        It is also possible to combine or subtract media groups
    Yamale is now used to validate Yaml

Overall the structure of the code is now much improved

diff --git a/.github/workflows/integrity-check.yml b/.github/workflows/integrity-check.yml
--- a/.github/workflows/integrity-check.yml
+++ b/.github/workflows/integrity-check.yml
@@ -4,18 +4,26 @@ on: [push]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v1
-    - name: Set up Python 3.7
+    - name: Set up Python 3.8
       uses: actions/setup-python@v1
       with:
-        python-version: 3.7
+        python-version: 3.8
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
+
+
     - name: Run tests
       run: py.test
+
+
+    - uses: actions/checkout@v1
+    - name: Build Yamale Recipe
+      run: python scripts/yamale_build.py
+    - name: Check diff
+      run: git diff --quiet -- || (echo "::error file=yamale,line=0,col=0::You need to run \`python scripts/yamale_build.py\`" && exit 1)
